/**
 * Icon registry — GENERATED FILE, do not edit by hand.
 *
 * Imports every icon, so import this only where the full set is genuinely
 * needed (the gallery, an icon picker). Product code should import individual
 * icons from './defs.js' to keep bundles lean.
 */

import type { IconDef } from './defs.js';
import {
  IconLockFill,
  IconKeyCrossFill,
  IconRoundCheckboxFill,
  IconLockStroke,
  IconKeyCrossStroke,
  IconRoundCheckboxStroke,
  IconUsdollarCurrency,
  IconXClose,
  IconSettingsFill,
  IconInboxFill,
  IconDashboardFill,
  IconSequenceFill,
  IconMeetingsFill,
  IconProductTourFill,
  IconSettingsStroke,
  IconInboxStroke,
  IconDashboardStroke,
  IconSequenceStroke,
  IconMeetingsStroke,
  IconProductTourStroke,
  IconInfoFill,
  IconWarningFill,
  IconIndicatorUpFill,
  IconIndicatorDownFill,
  IconInfoStroke,
  IconWarningStroke,
  IconIndicatorUpStroke,
  IconIndicatorDownStroke,
  IconCalendarFill,
  IconSearch,
  IconFilter,
  IconDropdownArrowUp,
  IconDropdownArrowDown,
  IconDropdownArrowLeft,
  IconDropdownArrowRight,
  IconSparklePointFill,
  IconPauseFill,
  IconSparklePointStroke,
  IconPauseStroke,
  IconUploadArrow,
  IconDownloadArrow,
  IconCheck,
  IconPromptTerminalFill,
  IconPresetDocumentFill,
  IconAutoReplyBubbleFill,
  IconAgentToolsFill,
  IconAllMessageBubbleFill,
  IconPresetCrossDocumentFill,
  IconConnectedPeopleFill,
  IconGuideBookFill,
  IconClientIdPeopleFill,
  IconSecretKeyShieldFill,
  IconCheckmarkCircleFill,
  IconWarningTriangleFill,
  IconLightBulbFill,
  IconSlackFill,
  IconTelegramFill,
  IconInternetBrowserFill,
  IconAssignedPeopleFill,
  IconLeadRepliesBubbleFill,
  IconBubbleCrossFill,
  IconUnreadBubbleFill,
  IconPromptTerminalStroke,
  IconPresetDocumentStroke,
  IconAutoReplyBubbleStroke,
  IconAgentToolsStroke,
  IconAllMessageBubbleStroke,
  IconPresetCrossDocumentStroke,
  IconConnectedPeopleStroke,
  IconGuideBookStroke,
  IconClientIdPeopleStroke,
  IconSecretKeyShieldStroke,
  IconCheckmarkCircleStroke,
  IconWarningTriangleStroke,
  IconLightBulbStroke,
  IconSlackStroke,
  IconTelegramStroke,
  IconInternetBrowserStroke,
  IconAssignedPeopleStroke,
  IconLeadRepliesBubbleStroke,
  IconBubbleCrossStroke,
  IconUnreadBubbleStroke,
  IconMentioned,
  IconWarning,
  IconLastActivity,
  IconCollapseDoubleArrowLeft,
  IconExpandDoubleArrowRight,
  IconTrunOffPower,
  IconGoToExternal,
  IconDragDot,
  IconSignalFill,
  IconSignalCrossFill,
  IconNotificationBellFill,
  IconCirlceRoundFill,
  IconXCirlceRoundFill,
  IconPeopleClientFill,
  IconThumbsUpFill,
  IconThumbsDownFill,
  IconFilterChatFill,
  IconBubbleMessageFill,
  IconRoom2peopleClientFill,
  IconNotesDocumentFill,
  IconImageFill,
  IconAutoCancelShieldFill,
  IconLazizaSparkleFill,
  IconLazizaCrossSparkleFill,
  IconSendPlaneFill,
  IconReasonQuestionFill,
  IconKeyFill,
  IconScheduleClockFill,
  IconSelectTimeClockFill,
  IconDeleteTrashFill,
  IconLocationPinFill,
  IconFailedErrorFill,
  IconBubbleFill,
  IconEyeCrossViewFill,
  IconEyeViewFill,
  IconComposerErrorFill,
  IconSignalStroke,
  IconSignalCrossStroke,
  IconNotificationBellStroke,
  IconCirlceRoundStroke,
  IconXCirlceRoundStroke,
  IconPeopleClientStroke,
  IconThumbsUpStroke,
  IconThumbsDownStroke,
  IconFilterChatStroke,
  IconBubbleMessageStroke,
  IconRoom2peopleClientStroke,
  IconNotesDocumentStroke,
  IconImageStroke,
  IconAutoCancelShieldStroke,
  IconLazizaSparkleStroke,
  IconLazizaCrossSparkleStroke,
  IconSendPlaneStroke,
  IconReasonQuestionStroke,
  IconKeyStroke,
  IconScheduleClockStroke,
  IconSelectTimeClockStroke,
  IconDeleteTrashStroke,
  IconLocationPinStroke,
  IconFailedErrorStroke,
  IconBubbleStroke,
  IconEyeCrossViewStroke,
  IconEyeViewStroke,
  IconComposerErrorStroke,
  IconAttachmentClip,
  IconTryAgain,
  IconRescheduleClockArrow,
  IconDownloadnSquareBoxLine,
  IconStageTripleLine,
  IconJobPostingArrowUpRight,
  IconRegenerateArrow,
  IconEditPencilArrow,
  IconPlus,
  IconRightArrow,
  IconLeftArrow,
  IconDoubleCheckRead,
  IconCheckRead,
  IconBoldFormat,
  IconItalicFormat,
  IconStrikethroughFormat,
  IconCodeFormat,
} from './defs.js';

export const iconSections: { section: string; icons: IconDef[] }[] = [
  {
    section: "paywall",
    icons: [IconLockFill, IconKeyCrossFill, IconRoundCheckboxFill, IconLockStroke, IconKeyCrossStroke, IconRoundCheckboxStroke, IconUsdollarCurrency, IconXClose],
  },
  {
    section: "panel",
    icons: [IconSettingsFill, IconInboxFill, IconDashboardFill, IconSequenceFill, IconMeetingsFill, IconProductTourFill, IconSettingsStroke, IconInboxStroke, IconDashboardStroke, IconSequenceStroke, IconMeetingsStroke, IconProductTourStroke],
  },
  {
    section: "dashboard",
    icons: [IconInfoFill, IconWarningFill, IconIndicatorUpFill, IconIndicatorDownFill, IconInfoStroke, IconWarningStroke, IconIndicatorUpStroke, IconIndicatorDownStroke, IconCalendarFill, IconSearch, IconFilter, IconDropdownArrowUp, IconDropdownArrowDown, IconDropdownArrowLeft, IconDropdownArrowRight],
  },
  {
    section: "onboarding",
    icons: [IconSparklePointFill, IconPauseFill, IconSparklePointStroke, IconPauseStroke, IconUploadArrow, IconDownloadArrow, IconCheck],
  },
  {
    section: "settings",
    icons: [IconPromptTerminalFill, IconPresetDocumentFill, IconAutoReplyBubbleFill, IconAgentToolsFill, IconAllMessageBubbleFill, IconPresetCrossDocumentFill, IconConnectedPeopleFill, IconGuideBookFill, IconClientIdPeopleFill, IconSecretKeyShieldFill, IconCheckmarkCircleFill, IconWarningTriangleFill, IconLightBulbFill, IconSlackFill, IconTelegramFill, IconInternetBrowserFill, IconAssignedPeopleFill, IconLeadRepliesBubbleFill, IconBubbleCrossFill, IconUnreadBubbleFill, IconPromptTerminalStroke, IconPresetDocumentStroke, IconAutoReplyBubbleStroke, IconAgentToolsStroke, IconAllMessageBubbleStroke, IconPresetCrossDocumentStroke, IconConnectedPeopleStroke, IconGuideBookStroke, IconClientIdPeopleStroke, IconSecretKeyShieldStroke, IconCheckmarkCircleStroke, IconWarningTriangleStroke, IconLightBulbStroke, IconSlackStroke, IconTelegramStroke, IconInternetBrowserStroke, IconAssignedPeopleStroke, IconLeadRepliesBubbleStroke, IconBubbleCrossStroke, IconUnreadBubbleStroke, IconMentioned, IconWarning, IconLastActivity, IconCollapseDoubleArrowLeft, IconExpandDoubleArrowRight, IconTrunOffPower, IconGoToExternal, IconDragDot],
  },
  {
    section: "inbox",
    icons: [IconSignalFill, IconSignalCrossFill, IconNotificationBellFill, IconCirlceRoundFill, IconXCirlceRoundFill, IconPeopleClientFill, IconThumbsUpFill, IconThumbsDownFill, IconFilterChatFill, IconBubbleMessageFill, IconRoom2peopleClientFill, IconNotesDocumentFill, IconImageFill, IconAutoCancelShieldFill, IconLazizaSparkleFill, IconLazizaCrossSparkleFill, IconSendPlaneFill, IconReasonQuestionFill, IconKeyFill, IconScheduleClockFill, IconSelectTimeClockFill, IconDeleteTrashFill, IconLocationPinFill, IconFailedErrorFill, IconBubbleFill, IconEyeCrossViewFill, IconEyeViewFill, IconComposerErrorFill, IconSignalStroke, IconSignalCrossStroke, IconNotificationBellStroke, IconCirlceRoundStroke, IconXCirlceRoundStroke, IconPeopleClientStroke, IconThumbsUpStroke, IconThumbsDownStroke, IconFilterChatStroke, IconBubbleMessageStroke, IconRoom2peopleClientStroke, IconNotesDocumentStroke, IconImageStroke, IconAutoCancelShieldStroke, IconLazizaSparkleStroke, IconLazizaCrossSparkleStroke, IconSendPlaneStroke, IconReasonQuestionStroke, IconKeyStroke, IconScheduleClockStroke, IconSelectTimeClockStroke, IconDeleteTrashStroke, IconLocationPinStroke, IconFailedErrorStroke, IconBubbleStroke, IconEyeCrossViewStroke, IconEyeViewStroke, IconComposerErrorStroke, IconAttachmentClip, IconTryAgain, IconRescheduleClockArrow, IconDownloadnSquareBoxLine, IconStageTripleLine, IconJobPostingArrowUpRight, IconRegenerateArrow, IconEditPencilArrow, IconPlus, IconRightArrow, IconLeftArrow, IconDoubleCheckRead, IconCheckRead, IconBoldFormat, IconItalicFormat, IconStrikethroughFormat, IconCodeFormat],
  },
];

export const allIcons: IconDef[] = iconSections.flatMap((s) => s.icons);
